$('.drag').draggable({
    appendTo: 'body',
    helper: 'clone'
});

$('#dropzone').droppable({
    activeClass: 'active',
    hoverClass: 'hover',
    accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
    //
    drop: function (e, ui) {
        var $el = $('<div class="drop-item"><details><summary>' + ui.draggable.text() +
            '</summary><div><label></label><input name="files[0]" type="file" class="form-control"/></div></details></div>');
        $el.append($('<button type="button" class="btn btn-default btn-xs remove"><span class="glyphicon glyphicon-trash"></span></button>').click(function () { $(this).parent().detach(); }));
        $(this).append($el);
    }
}).sortable({
    items: '.drop-item',
    sort: function() {
        $( this ).removeClass( "active" );
    }
});